site_name: ICADCML 2021 Neural Encryption Networks
theme:
  name: "material"
  palette:
    primary: "dark-blue"
    accent: "dark-blue"
    # scheme: slate Use this for dark mode
    # scheme: slate
    scheme: default

docs_dir: templates
repo_url: https://github.com/oke-aditya/neural_encryption_networks
markdown_extensions:
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
extra_javascript:
  - https://unpkg.com/mermaid@8.4.4/dist/mermaid.min.js

nav:
  - Home: index.md
  - Autoencoders: autoencoders.md
  - Mapping: mapping.md
  - Encrypting Data: neural_enc.md
  - Securing With Keys: keys.md
  - References: references.md
